bookeeper_manager:
    resource: "@BookeeperManagerBundle/Resources/config/routing.yml"
    prefix:   /book

platform:
    resource: "@PlatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
